spring:
  profiles:
     active: s1
  application:
    name: service-front 
  http:
    encoding:
      charset: UTF-8
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
      
  data:
    elasticsearch:
      cluster-name: cloudPlat
      cluster-nodes: 192.168.6.88:9300,192.168.6.89:9300,192.168.6.90:9300
      repositories:
        enabled: true
        
        
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
      enabled: true
      
debug: true
